#!/usr/bin/env bash

if [ "$#" == "0" ]; then
    echo "Usage: `basename $0` PROJECT" >&2
    exit 1
fi

proj=$1
bin_dir=`dirname $(readlink -f $0)`

# Include config file
source $bin_dir/config

if [ ! -d $proj ]; then
    echo "Project $proj doesn't exist, aborting."
    exit 1
fi

avconv -r $fps -start_number 1 -i $proj/shot%d.jpg -vcodec mpeg4 $proj.avi
